[package]
name = "sugarflower"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }
linked-hash-map = "0.5.6"
encoding_rs = "0.8.32"
clipboard = "0.5.0"
anyhow = "1.0.71"
csv = "1.2.1"
rand = "0.8.5"
toml = "0.8.13"

[lib]
path = "src/lib.rs"

